### ISSUE TITLE
implement topographic isolation

### ISSUE THREAD

**Issue by der-stefan** [der-stefan/OpenTopoMap#10]
esp. for mountains

German: Dominanz (https://de.wikipedia.org/wiki/Dominanz_%28Geographie%29)

**Comment by nebulon42** [comment]
maybe interesting: https://github.com/k127/osm-peak-dominance

**Comment by max-dn** [comment]
I did some tests because this issue [came up in the openandromaps forum](https://www.openandromaps.org/oam-forums/topic/anzeige-berggipfel-in-elevate-le/page/2/#post-20920)... It's possible to calculate isolations in reasonable time (initial ~1h, updates in minutes), but at now I have no idea how to use these data for the style...

May we add a column "isolation" or "otm_isolation" to planet_osm_point to store the isolation? It's not necessary to read these data while importing, a simple `ALTER TABLE planet_osm_point ADD COLUMN otm_isolation text;` after import would do it.

**Comment by der-stefan** [comment]
Good idea, but let's write a little script to do that. Because in some years I forget how to do it...
I will manage the style if you manage the calculations. :-)

**Comment by max-dn** [comment]
I just made PR. If that works we will have column with topographic isolations. The next step will be the hard work of integrating these numbers in the style.... I wrote something about the program in the [OSM-Wiki](https://wiki.openstreetmap.org/wiki/User:Maxbe/Dominanz_von_Gipfeln).

**Comment by max-dn** [comment]
Just to have something to start and to get an idea, what could be done with isolations... For sure we have to adjust some (all?) rules:

Till now, all symbols are rendered in Zoom 12-17, names are drawn in Z12-17, ele is drawn in Z13-17

I tried the following settings:

- Zoom 9: Symbol for Isolation>25000
- Zoom 10: Symbol for Isolation>8000, name for Isolation >16000
- Zoom 11: Symbol for Isolation>3000, name for Isolation >6000
- Zoom 12: Symbol for Isolation>1200, name for Isolation >1200
- Zoom 13: Symbol for Isolation>300, name+ele for Isolation >300
- Zoom 14-14: Alls symbols, name and ele

In [alpine regions](https://geo.dianacht.de/bilder/wetterstein_iso_1.png) it seems ok. Some peaks are hidden behind a train station. Some are surprisingly missing, because their isolation is not as large as their touristic significance, but it seems ok.
In [not so hilly areas](https://geo.dianacht.de/bilder/erlangen_iso_1.png) there are no big changes. 

Maybe small peaks on islands will be a problem. They have large isolations (and all other technical parameters, like the height/prominence-ratio) but still they are small hills on small islands...

**Comment by der-stefan** [comment]
Great job by you, once again! Thank you very much, @max-dn !

**Comment by der-stefan** [comment]
There is a problem with the Moritzberg: https://opentopomap.org/#map=17/49.46629/11.31321
The OSM peak and the DEM peak are ~100 meter displaced. And in OSM the ele is correctly mapped as 603 meters, whereas the DEM gives ~625 meter, due to dense forest. Therefore, the isolation algorithm calculates a value of 135.
Is it bad luck for Moritzberg or can we relax the conditions a little bit?

**Comment by max-dn** [comment]
I first had MINDIFF=30, then changed this to 10. I think every value 10..30 is ok. So lets take 20. Now the Moritzberg gets an isolation of 9343 and the next higher point is near Arzberg: https://www.opentopomap.org/#map=14/49.48003/11.43994

**Comment by der-stefan** [comment]
@max-dn: Could you have a look at the two peaks north of Erlangen? The parameter otm_isolation is shown in the screenshot:
![isolation](https://user-images.githubusercontent.com/3618939/33736010-68fcdef6-db91-11e7-8aae-0a653123d4d5.png)

How is it possible to have two isolation values (8485 and 6686) in a distance of only 1.8 km?

**Comment by max-dn** [comment]
They both have no ele=* and get the same hight (391) from the DEM. 
If they had different heights, the first rule "find the next higher peak" would break the lowers isolation, but not in this case. The second rule "find the higher point in DEM" finds for both a point at [49.62049.11.04432](http://www.openstreetmap.org/node/257505817#map=18/49.62049/11.04432) in distance 6.6 and 8.4km.

First we had a rule "find a peak with same hight or higher". I changed that to "higher" after I found the both peaks of Teide (nodes 3281761453 and 32969695). An alternative could be a rule "the northern peak wins" or "the lower osm_id wins".
