### ISSUE TITLE
viewpoint directions

### ISSUE THREAD

**Issue by der-stefan** [der-stefan/OpenTopoMap#109]
Let's not forget the viewpoint direction issue:
https://forum.openstreetmap.org/viewtopic.php?pid=261496#p261496

Just an idea: could we do it dynamically as a SVG?

**Comment by mboeringa** [comment]
@der-stefan : #77 ;-)

**Comment by der-stefan** [comment]
Of course we need a (pre?)processing of the wild direction values. We need to find out, how many "beams" are ok for rendering. Perhaps we should define an angle for the beams itself and an angle between beams. With those fixed values we can assemble the icon.
Regarding your points in the same order:

- Only few are tagged, because they are ignored by all map style I know...
- Yes, we should interpret a single direction as a half circle.
- Multi-range viewpoints are hard to process, but in the real world they can be reasonable. But for a start we could ignore them.
- direction=clockwise doesn't make sense, does it?

**Comment by max-dn** [comment]
I think processing should be possible while rendering, it's just some string processing...

For testing I have 7 icons with angle 60-360°:
![viewpoints](http://geo.dianacht.de/bilder/otm_viewpoints_1.png)

No, direction=clockwise doesn't make sense.
Some have "direction=360°". That's eqal to "direction=north", but perhaps I will interpret that as "direction=0-360".

**Comment by mboeringa** [comment]
> Some have "direction=360°". That's eqal to "direction=north", but perhaps I will interpret that as "direction=0-360".

I would really stick to the Wiki documented formats, and reject poor tagging. That way, people will be forced to apply proper tagging if they want to see it rendered with direction. Trying to support every possible permutation will quickly lead to unwieldy code...

**Comment by max-dn** [comment]
Just to have something to discuss about I have rendered some viewpoints with [this function](https://github.com/max-dn/OpenTopoMap/blob/viewpoint/mapnik/tools/viewpointdirection.sql):
![otm_vp_V2](http://geo.dianacht.de/bilder/otm_viewpoints_2.png)

The rules:

* angles are rounded to a small number of icons (at the moment 60, 90, 135, 180, 225, 270, 360°)
* a full circle ist a empty direction or "0-359" or "0-360" (or "E-E")
* all cardinal directions are allowed, eg "N-S" == "N-180" 
* negative values may lead to surprising results (-45=NW, but a range "-30 - -80" is not accepted and rendered as full circle)
* a single direction is a viewing angle of 135° around this direction (180 seems too wide, because the beams are too thick, maybe we may change this with better icons).
* if there are two directions separated by semicolon
  *  a single direction is only 90°. That's because I think "N;S" is valid and should be rendered.
  *  the gap between the these two icons must be > 45. If not, we try to fill the gap ("0-30;180-190" in the image above"). Sometimes this gap is not in the data, but a result of our rounding.
* Maybe we can fix some errors (all expressions we can't parse are considered as "0-360", but we do not fix overlapping angles like the red ones above ("N-E;NNE-S" and "N--W;100-110").
 
Todo: Have a look at the viewpoints Budapest and do some (performance!) tests. Get some more nice icons ;)

**Comment by mboeringa** [comment]
Personally, I would reject input not following the OSM Wiki direction page. Lower case cardinal is probably OK, but I would not support "seaside". It is stupid. If we start describing types of viewpoints (e.g. "mountain top", "high rise", "tree top"), the possible permutations are endless...

**Comment by max-dn** [comment]
"seaside" is an example of a invalid input. It's just rendered as circle, same as "tree top" or an empty direction. directions are case insensitive, because I first convert all to lower case and throw away all characters I can't use (like "°").

**Comment by max-dn** [comment]
I tested on errors with all directions we have. False tagging is a really minor problem. Out of 509 different directions there are 17 with errors.

**Not interpreted** are 17 directions with
* wrong delimiter ("315,225", "E / S", "E / S / W", "E,SE")
* wrong cardinals? (ENEW, NO, SWW ...)
* some other text ("forward", "clockwise")

These directions are rendered like "0-360".

**Not interpreted as "0-360"** is "360" or "360°". These dirctions are handled in the same way as "N"

We have only 5 viewpoint directions with two ranges, only one is rendered with two segments. Two of them have only 2 segments because people didn't want to cross north, I think.
* 0-30;170-360 has a really small gap between 360 and 0  -> after rounding its one segment 177-42
* 070-180;190-340 too small gap 180-190 -> one segment 71-341
* 100-280; 350-80 too small gap 80-100 -> one segment  0-270
*  247-360;0-157 too small gap 360-0 -> one segment 236-146
* 115-170;290-310 -> two segments 113-173 and 270-330  **yeah!**

Performance seems not to be a problem. We have to call this function 4 times for each viewpoint, because I didn't find a way to access a composite type with mapnik. But in most cases this function returns after 4 lines of unexpensive code ;)

**Comment by max-dn** [comment]
I made two cities. It's not really impressive, but maybe viewpoints shouldn't be the most impressive object on a map ;) 

In Budapest most viewpoints are nearly invisible between all the buildings. And they are more invisible if they are not full circles. The [small viewpoint](http://www.openstreetmap.org/node/735462396#map=19/47.49821/19.03944) (45-120) next to the roundabout is nice....

![Budapest](http://geo.dianacht.de/bilder/otm_viewpoints_3.png)
[Budapest](http://www.openstreetmap.org/#map=17/47.49613/19.04030) Zoom=17

With less buildings I think it looks ok...
![Salzburg](http://geo.dianacht.de/bilder/otm_viewpoints_4.png)
[Salzburg](http://www.openstreetmap.org/#map=16/47.8037/13.0551) Zoom=15

**Comment by der-stefan** [comment]
This is very, very nice! What about enabling it in the online version?

**Comment by mboeringa** [comment]
> This is very, very nice! What about enabling it in the online version?

+1
