### ISSUE TITLE
Move repository

### ISSUE THREAD

**Issue by der-stefan** [der-stefan/OpenTopoMap#171]
Depending on futher developments at Github we should figure out, if moving the OTM repository to some other server is necessary. Our criterias:

- git instance
- Ability for users to open issues
- Ad free web interface
- Free of charge

There are open source graphical web frontends that could be installed on our own server. Or we could migrate to another free platform.

**Comment by max-dn** [comment]
For now, I see no reason, but we should be prepared... The problem is not the source code (every one may have the complete source+history in his fork), but the issues. A lot of documentation, why and how something was done (and why something was not done) is documented in issues...

Maybe [someone will build soemething for OSM projects](https://forum.openstreetmap.org/viewtopic.php?id=62534). If not, a self hosted Gitea with oauth to OSM could be worth a look.

**Comment by der-stefan** [comment]
Ok, I don't care as long as the infrastructure still works. Let's invest our time into MAPS instead.
