### ISSUE TITLE
contour line colors

### ISSUE THREAD

**Issue by sarnila** [der-stefan/OpenTopoMap#210]
Contour lines come out very light brown and are hardly visible on my Fenix 5X Plus. I have also build lines using your HOWTO. Where can the color be given?

**Comment by der-stefan** [comment]
@sarnila You were faster than me - thanks for posting the solution here.

**Comment by MacL3an** [comment]
I just tried following the instructions in the [README](https://github.com/der-stefan/OpenTopoMap/blob/master/garmin/README.md), and finally got one .img file for the country (Sweden) that I'm trying to generate non-brown contours for. This file did not seem to contain any contours when I loaded it to my watch. I will try to send a PR to update the README, since some things seemed outdated/links broken. 

I started to suspect something was missing from the instructions so I found this **deleted** [HOWTO](https://github.com/der-stefan/OpenTopoMap/blob/52fdc8f15342ebec5afe93c5a5a3258c712b1b7c/garmin/HOWTO), with instructions about contours which then lead me here: http://katze.tfiu.de/projects/phyghtmap/#MacOSXDependencies, with a link to the Enthought Pyhon Distrivbution, which is no longer available, which is where I finally gave up. 

Do you have any advice @sarnila or @der-stefan? Any instructions that I'm missing? All I want is to create contours that are not light brown and impossible to see in daylight on my Fenix watch.
