### ISSUE TITLE
CTRL++++ intercepted, so no way to make fonts bigger

### ISSUE THREAD

**Issue by jidanni** [der-stefan/OpenTopoMap#246]
The words on the map are too small for me.
So I do CTRL+++++... in my browser.
But that causes the zoom level to increment and tiles to be replaced.

So there is no way to see things bigger (web accessibility issue).

So please do like osm.org website, and don't intercept CTRL++++...

Just let it do like it would normally.

**Comment by Juergeen** [comment]
Just tested that with Firefox and Chrome: Pressing Ctrl-NumericPlus or Ctrl-NumericMinus works as expected and in fact increases/decreases words on the map with the zoom level of the browser instead of the zoom level of the map as visible in the URL.  
If this issue cannot be reproduced by somebody else, it might already have been fixed in the meantime.
