### ISSUE TITLE
Die Kacheln können unter folgendem Pfad abgerufen werden

### ISSUE THREAD

**Issue by flux242** [der-stefan/OpenTopoMap#248]
https://{a|b|c}.tile.opentopomap.org/{z}/{x}/{y}.png

What's a|b|c? It is a switch for what? Load balancing? Different layers? Please clarify

**Comment by max-dn** [comment]
It's the same layer. Most Browsers have a limit of parallel connections to the same host. That's bad for tiled maps because there you will need 30 or 50  tiles at one time. To allow more connections, the tile server has 3 names to trick the browser. It could be used for load balancing, but is not, because there is only one server...

**Comment by der-stefan** [comment]
It is a.tile.opentopomap.org **or** b.tile.opentopomap.org **or** c.tile.opentopomap.org. That offers client-side load balancing if there are more tile servers. In our case there is just one...
