### ISSUE TITLE
Split repositories for Garmin and Mapnik?

### ISSUE THREAD

**Issue by nebulon42** [der-stefan/OpenTopoMap#49]
Does it make sense to have Garmin and Mapnik style in two separate repositories? Is there the need to have all changes to the Mapnik style also in the Garmin style and vice versa or are they distinct projects?

**Comment by der-stefan** [comment]
Ok, they are two different projects. I have feedback that some people set up their own OTM Mapnik server, but nothing about OTM Garmin yet. And since I am the very only developer right now, I don't see any need to split up the projects into two repositories. If, and when, the numbers of developers increase and do daily commits, I will consider a split. :-)
