### ISSUE TITLE
Update mkgmap

### ISSUE THREAD

**Issue by utack** [der-stefan/OpenTopoMap#52]
New mkgmap versions produce 5-10% smaller maps:
http://www.mkgmap.org.uk/pipermail/mkgmap-dev/2016q3/025012.html
Would be nice to take advantage of it, it saves bandwith on the servers too

**Comment by der-stefan** [comment]
Good idea. Some day we give it a try.

**Comment by der-stefan** [comment]
In my tests there was no difference in file size. But anyway, the next time we touch the Garmin toolchain, we will update mkgmap. I close this issue because I won't forget it. I just have no clue, when this will happen.......................................................................................................................

**Comment by utack** [comment]
>In my tests there was no difference in file size.  
  
Odd  
Thanks for checking though!
