### ISSUE TITLE
Suggestion add natural=saddle

### ISSUE THREAD

**Issue by krisanselmo** [der-stefan/OpenTopoMap#54]
As all topographic map it could be interesting to see the mountain passes.

**Comment by der-stefan** [comment]
https://wiki.openstreetmap.org/wiki/User:Maxbe/Kartenversuch#Ausrichtung_von_P.C3.A4ssen_und_S.C3.A4tteln

**Comment by max-dn** [comment]
I will try to do something similar, based on contour lines. If someone else wants to do it, maybe with an other/better aproach, feel free. I'm not sure I will succeed and I will need weeks, maybe months...

**Comment by der-stefan** [comment]
@max-dn Thanks for joining the discussion! Your work on generalizing OSM data is terrific. If I had more time I would have implemented your algorithms in OpenTopoMap, too. But time for people like us is always a problem.

**Comment by max-dn** [comment]
Just as a sample, made with [this function](https://github.com/max-dn/OpenTopoMap/blob/master/mapnik/tools/saddledirection.sql): What we could get is something like that: [s1.html](https://geo.dianacht.de/otmtest/s1.html?layers=B00T) (be patient, its slow). About 50% of the saddles got the right direction, 25% are somehow "ok" and 25% are completely wrong. 
![Mieminger](http://geo.dianacht.de/bilder/miemingersaddle1.png)

They are wrong in situations [like here at Hölltörl](https://geo.dianacht.de/otmtest/s1.html?layers=B00T&zoom=16&lat=47.34256&lon=10.91915) (lower left corner in the image above), where the saddle point doesn't match the contour lines.
![Hoelltor](http://geo.dianacht.de/bilder/hoelltorsaddle1.png)

Saddles with already tagged direction=* will be rotated in this direction not in the calculated one.

It's a little bit slowly to calculate the orientation of each saddle point each time the map is rendered. We could write back the result to planet_osm_point so it's only calculated once until the next update of this node. Maybe thats a license issue, because we create a database table with content from osm and from the elevation data. With PD data like SRTM that should be ok, in the worst case OpenTopoMap has to provide a database dump with id and calculated directions as odbl-data if someone ask for it.

The communication between the database with the osm data "gis" and the "contours"-database is done with [dblink_connect_u](https://www.postgresql.org/docs/9.1/static/contrib-dblink-connect-u.html). This could be a security flaw but I think it's not in a environment with one user owning both databases on a local machine.

**Some questions:**

- What shall be rendered? I would suggest natural=saddle and natural=col (not in the wiki, but in use maybe a little bit smaller icon). What about natural=notch (in the wiki, but rarely used)?
- Whats the best icon? Something like )( or ][ ... should be different from bridges...
- And the last question: Is this hit rate worth the effort? At least at the first time it will take a second or so for each saddle to get the direction... On the other hand it could look good and maybe wrong directions are a good motivation for people to use the direction-Tag (which would reduce the effort in the long term)...

@der-stefan 
- could you tell me the srid of the tables? 0, 900913 oder 3857?
psql gis -c "select srid from geometry_columns where f_table_name='planet_osm_point';"
psql contours -c "select srid from geometry_columns where f_table_name='contours';"
I have tried to get the same database layout, but I'm not sure...
- Is it ok to write the calculated directions back to planet_osm_point? Has the user for the renderd write access to this table?
- Is it ok to use dblink_connect_u? You are using dblink_connect already for populating the lowzoom-database, but only as postgis, not as a normal user.

**Comment by max-dn** [comment]
[Next version](https://geo.dianacht.de/otmtest/s1.html?layers=B00FT)... now calculated with some more contour lines in the area of the saddle point. Shout be less sensitive to slightly displaced nodes or elevation data:

![mieminger v2](http://geo.dianacht.de/bilder/miemingersaddle2.png)

I have problems with saddles in plain areas ([here](https://geo.dianacht.de/otmtest/s1.html?layers=B00FT&zoom=14&lat=47.44946&lon=12.29855) for example). Thats a pity because these are the areas where roads are an one can easily see the error but I think we can't solve it. We need at least 2 different contour lines next to the saddle.

**Comment by mboeringa** [comment]
Really nice. 

Ultimately though, I would strive to get the dynamically calculated pass direction as soon as possible entered in the direction tag of the mountain passes in OSM. This way, you don't have to calculate them all the time, as I don't think this type of calculation is really feasible on a global scale dynamically.

Having such a pre-calculated value, that can then be checked by real mappers, would be great I think. It is quite tiresome to do add this info manually checking aerial and contours for large numbers of passes (as I experienced adding some around Val di Mello in Italy).

**Comment by max-dn** [comment]
@der-stefan, forget my question about write permissions to planet_osm_point. I have learned that [Mapnik makes always read-only connections](https://github.com/mapnik/mapnik/issues/2142). So if you don't want to estimate every saddle for every tile you have to do the calculation for new updated saddles with a cron job, Something like "update point set direction=getsaddledirection() where direction is null" will update every saddle which was updated in OSM since the last run.

@mboeringa: these data are good enough for a nice map feature, but not good enough for the OSM database.
- we have bad elevation data in wide areas and some good data which could cause license issues...
- we have a lot of natural=saddle not at the correct topographic saddle point. The node is often mapped where the highway=* is, next to the signpost or souvenir shop and that is not always the deepest point.
- the algorithm has no mathematical principle and has some known flaws (e.g. we consider every contour line only once. In most cases the lower contour line has 2 points next to the saddle, one one each side)
-  the algorithm has 4 or 5 parameters one could discuss. (e.g. why not take only the next 3  contour lines, or maybe leave aside the first 500m to get a more generalized direction for lower zoom level)

So we will still need to map directions manually, best by visiting these points ;)

**Comment by max-dn** [comment]
First demo. 

In alpine area (sorry for the glitches in hillshade)
![Saddle demo 1](http://geo.dianacht.de/bilder/saddle_renderdemo_1.png)

On a road (Zoom 16)
![Saddle demo 1](http://geo.dianacht.de/bilder/saddle_renderdemo_1a.png)

* Maybe the icon should be more visible in Zoom 13+14, but I'm biased now. Saddles are not as important as alpine huts or peaks... 
* There is a lot of space between icon and label, because we have to reserve space for a saddle in north-south direction. At the "Grünsteinscharte" the space is ok, at the both "Tajatörl" it seems to be too much.

**Comment by der-stefan** [comment]
@max-dn Great work! Answers to your questions:
- SRID=3857
- I don't see a problem to write the direction back to the main database. As you stated, a cron job is the better option.

**Comment by der-stefan** [comment]
This issue is completely implemented. Thank you very much, @max-dn!
