### ISSUE TITLE
mapnik/HOWTO_Ubuntu_16.04 issues

### ISSUE THREAD

**Issue by ktye** [der-stefan/OpenTopoMap#70]
There are some issues in the documentation:

1. installation of rendred is missing
$ sudo dpkg -i rendered_*.deb # Line:87 (before installing libapache2-mod-tile)

2. run psql commands as user postgres
Line:117 (exit) should be a the end of the block, otherwise L118 (createdb) fails.
Line:119 strip "sudo -u postgres", this is not needed anymore

I couldn't get past HOWTO_DEM, see next issue.
 
On a side note, I use debian 8.6 which works quite similar, except some libraries are older:
postgresql-9.4
postgresql-9.4-postgis-2.1
libmapnik-2.2
I hope my problems are not related to this.

**Comment by int19h** [comment]
Note that if you use Debian unstable, you'll get newer packages (postgresql-9.6, libmapnik-3.0).

**Comment by der-stefan** [comment]
1. renderd is not used anymore. Instead we use tirex now. But mod_tile is still required for Apache, of course.
2. "sudo -u" is a typical Ubuntu command in order to execute something as a different user. This can be different in Debian. But at least it should be clear that you need to think about user permissions of the database and the renderer.
