### ISSUE TITLE
World TIFF/HGT not complete - another source?

### ISSUE THREAD

**Issue by tds4u** [der-stefan/OpenTopoMap#73]
Hello,
I've downloaded whole World TIFF/HGT files, but it seems that something is broken? Greenland is not there and north/south pole part is missing. If I download everything (Axx-Zxx, AAxx-ZZxx) there are many holes.
Is there a way to have data source which is completed or check against errors?

Hillshade 5000
![image](https://cloud.githubusercontent.com/assets/5459443/21965656/a4611c42-db64-11e6-85fc-23fba7b1bcbf.png)

**Comment by der-stefan** [comment]
Yes, Greenland is missing in the 30m SRTM data. Have a look at www.viewfinderpanoramas.org for a global void filled DEM. If you are patient, you can wait for the release of NASADEM...

**Comment by tds4u** [comment]
Thanks for the hint. Tried other source and  ... look:

![image](https://cloud.githubusercontent.com/assets/5459443/22052500/df5b80f2-dd4a-11e6-97f5-ac8276afe39a.png)

Btw, exporting contour lines to PBF for osm2pgsql gave errors (**MemoryError**):
```
Traceback (most recent call last):
  File "/usr/local/bin/phyghtmap", line 11, in <module>
    load_entry_point('phyghtmap==1.71', 'console_scripts', 'phyghtmap')()
  File "build/bdist.linux-x86_64/egg/phyghtmap/main.py", line 577, in main
  File "build/bdist.linux-x86_64/egg/phyghtmap/main.py", line 330, in processHgtFile
  File "build/bdist.linux-x86_64/egg/phyghtmap/hgt.py", line 384, in __init__
  File "build/bdist.linux-x86_64/egg/phyghtmap/hgt.py", line 439, in initAsGeotiff
  File "/usr/lib/python2.7/dist-packages/osgeo/gdal.py", line 2469, in ReadAsArray
    callback_data = callback_data)
  File "/usr/lib/python2.7/dist-packages/osgeo/gdal_array.py", line 345, in BandReadAsArray
    buf_obj = numpy.empty([buf_ysize,buf_xsize], dtype = typecode)
MemoryError
```
Can you give me a point where to start?

**Comment by der-stefan** [comment]
Oh yes, phyghtmap can only handle small files. I used it for creating the small extracts for the Garmin maps.

**Comment by timautin** [comment]
I also have the memory error with phyghtmap (I have 64GB). @der-stefanc, could you tell us how did you do it for the whole world?

**Comment by der-stefan** [comment]
@timautin We use the contour lines kindly provided by opensnowmap. For the Garmin maps of single countries, phyghtmap works fine.

**Comment by timautin** [comment]
Oh I see, thanks. I didn't find a link to download the data from OpenSnowMap. I guess it's too big and they only provide it upon request?

**Comment by der-stefan** [comment]
Yes, the contours require more space than the global OSM database! Our contours database consumes around 500 GB on the SSD - without indices.

**Comment by timautin** [comment]
Thanks for the answer. In the end my contours DB is indeed a little bit bigger than the OSM one. I didn't expect that (I thought OSM would be much bigger with all the roads, landuse etc), but if I simplify my contours a bit more to reduce the space they look ugly.

**Comment by carlos-mg89** [comment]
Wow! I had never expected contours / hill shades to take so much space :( I guess I'd go with the option of generating them for a smaller portion of the world.

**Comment by carlos-mg89** [comment]
@der-stefan how much memory do I need in a computer to generate the world contour lines data (last step https://github.com/der-stefan/OpenTopoMap/blob/master/mapnik/HOWTO_DEM.md#create-contour-lines ) ?

Right now I'm trying with a smaller set of .hgt files, since the world ones simply took all my RAM (not much, 32 GB). And the smaller set I'm processing is for Spain and France area. This takes the 32 GB of RAM as well, and about 45 GB of a swap file I've created in my SSD.

If I wanted to create them for Europe, how big should my swap file be?

Is there any way of doing this process in chunks, let's say, per country, and then merge the results in a common .pbf file?

Thanks for answering back, and apologies if I should really have created a new issue, but I thought most of my questions shared scope with this one.

**Comment by sletuffe** [comment]
If the tool is inapropriate for your task then... change the tool :-)
gdal_contour has the ability to convert from tiff files to postgis enabled database in one step. And without memory exhaustion.

**Comment by carlos-mg89** [comment]
Thanks for replying @sletuffe !

Alright, that sounds like an interesting approach. Would you be able to point me how to convert from this:

` phyghtmap -o contour --max-nodes-per-tile=0 -s 10 -0 --pbf warp-90.tif`

Into using gdal_contour to load the data into a database? Or to modify that command so it loads the data from a database instead of the warp-90.tif file? I haven't been able to see anything about this in the phyghtmap documentation ( http://katze.tfiu.de/projects/phyghtmap/phyghtmap.1.html ) nor in the gdal_contour documentation (https://gdal.org/programs/gdal_contour.html).

Thanks in advance! I'm looking forward to understand how all of this works :)

**Comment by carlos-mg89** [comment]
It seems I've found something that would help me, although I haven't tried it yet since the previous run of 'phyghtmap' is still going on.

This seems to be the code for gdal_contour to load a tif raster file into the PostgreSQL database:
`gdal_contour -f PostgreSQL -i 1 -nln cont iamrast.tif "PG:host=localhost user=iampg password=iampgpass dbname=iamgis"`

By reading the documentation, gdal_contour will transform the raster data into vector data, to store it later into a database in this case, instead of a PBF file.

I guess that later I'd be able to serve the contour vector lines using the PostgreSQL and some tile server, right? At the moment, I'm using tessella (https://github.com/urbica/tessella) to serve a big MBtile for Europe as vector PBF. I can see there's an option to serve PostGIS, but I don't think that refers to PostgreSQl.

If anyone could spread some light, it would be more than welcome :)

**Comment by carlos-mg89** [comment]
I'm already loading the DEM data for Spain and France after I generated the warp 90.

PostGIS is indeed PostgreSQL, with the GIS extension. Thanks for the hint @sletuffe .

It seems to be working quicker than the `phyghtmap` alternative, right now is at about 45% of the reading, with no new data inside the database yet, but waiting for it.

I was just wondering how can a partial load be done, for smaller chunks. Just as I'm doing now, but using a TIFF file that was made using the .hgt files for the areas of the world I'm interested in? Or would that corrupt the data in the DB?

Thanks in advance and appreciate a lot your previous help.

**Comment by strongwillow** [comment]
@carlos-mg89 , you can download DEM you need here: http://www.viewfinderpanoramas.org/Coverage%20map%20viewfinderpanoramas_org3.htm

Then you can just combine those using `gdal_merge.py`
