### ISSUE TITLE
Rotate stations

### ISSUE THREAD

**Issue by der-stefan** [der-stefan/OpenTopoMap#74]
Railway stations could be rendered more intelligent by rotating the symbol according to the rails. Here is an example:
![station](https://cloud.githubusercontent.com/assets/3618939/22000720/161579fa-dc41-11e6-8a6b-c071831f24aa.png) ![station2](https://cloud.githubusercontent.com/assets/3618939/22000723/19aa4cda-dc41-11e6-9851-0c0aa2509d5a.png)

**Comment by max-dn** [comment]
Is it worth 15 minutes preprocessing after each update of the database?
I think we could rotate the station in the direction of the next some rails, but that needs some expensive geometric queries for each station to find the rails and some cheap queries to get their direction...

**Comment by der-stefan** [comment]
Yes, 15 minutes for a worldwide preprocessing is fine. There could be a problem when multiple stations are above each other in different directions (I can't give an example). A terminus ("Kopfbahnhof") could make trouble, too.
Perhaps we could make it similar to the mountain passes: Save a direction in the database. And for further runs we don't process the direction again, if it is already in the database. (Thinking about minutely diffs again...)

**Comment by severak** [comment]
(another workaround is to use circles for station symbols)

**Comment by max-dn** [comment]
I tested some stations in [Erlangen and Paris](https://geo.dianacht.de/otmtest/stations1.html) with [this script](https://github.com/max-dn/OpenTopoMap/blob/stations/mapnik/tools/stationdirection.sql)... Paris because there are [real terminal stations](https://geo.dianacht.de/otmtest/stations1.html?zoom=17&lat=48.88086&lon=2.35447&layers=BT).

The distinction between terminus and "normal station" works, but the layers make problems. Stations are mostly at layer=0, their rails may be at layer=-1 like [here](http://www.openstreetmap.org/node/2499357757). I could handle that by taking the next rail which is at the same layer as the station and if that fails taking just the next rail. That leads to the next problem: In [Fischbach](https://geo.dianacht.de/otmtest/stations1.html?zoom=15&lat=49.41436&lon=11.17388&layers=BT) we have a station at layer=0 and rails on a bridge. The next rail on layer=0 is next to the bridge and for this rail this station seems to be a terminus...

**Comment by der-stefan** [comment]
Wow, good work so far. I can see the problem with short bridges. But should a terminus really be turned by 90 degree? Perhaps it is fine to make no distinction...

By the way: Subway stations should be excluded.

**Comment by max-dn** [comment]
> But should a terminus really be turned by 90 degree?

For real terminal station (a lot of rails and a building crosswise at their end) I think it would be nice. But in OSM a lot of them are not mapped at the building but in the middle of the platforms ([1](http://www.openstreetmap.org/#map=18/48.78541/9.18241) [2](http://www.openstreetmap.org/#map=18/48.19662/16.33561) [3](http://www.openstreetmap.org/#map=18/22.55603/88.31477)). That's why I went to Paris ;)

> Perhaps it is fine to make no distinction...

Jep, I think it's better and solves the problem with bridges. It's unlikely that we find a station where the station has a very different direction than the rail next to the bridge. Rails ar not very curvy.

**Comment by max-dn** [comment]
[Demo without terminal stations and subways](https://geo.dianacht.de/otmtest/stations2.html) 

We have still to calculate with railway=subway, because some [railway=station](http://www.openstreetmap.org/node/903229638) are not tagged as subway, but belongs to a [subway rail](http://www.openstreetmap.org/way/255909840)

**Comment by der-stefan** [comment]
If some stations are tagged wrong or incomplete, it is not the subject of our renderer to try to fix the error. Perhaps our map style even animates people to correct those mistakes... (It would be important to keep our database more up-to-date... Damn... ;-)

railway=halt are interesting for us, too. We could calculate and save the direction, but render halts differently (lighter, inly starting from higher zoom level).

There is a problem with [Neuperlach Süd](https://geo.dianacht.de/otmtest/stations2.html?zoom=17&lat=48.08895&lon=11.64516&layers=BT) and I can't see why. There is no rail on a different layer going from north to south.

**Comment by max-dn** [comment]
[Neuperlach](http://www.openstreetmap.org/node/2476467535) ist rotated in direction of a [historic tram](http://www.openstreetmap.org/way/366760775) ... With "railway IN ('funicular', 'light_rail', 'monorail', 'narrow_gauge', 'rail', 'preserved', 'subway')"  Neuperlach is in direction 144 (SE). 

I took every kind of rail because I found some stations along abandoned rails. We should be more restrictive, set an error return to NULL and set just sqares for stations without known direction.

An other problem was fixed: [Stachus](https://geo.dianacht.de/otmtest/stations2.html?zoom=16&lat=48.13897&lon=11.56744&layers=BT) got its direction from a rail which is in [a tunnel on the surface](http://www.openstreetmap.org/way/308889241). Now we interpret tunnel=* as "not on layer=0"  and Stachus is in direction 128.

**Comment by der-stefan** [comment]
What about sorting the rails to look at by their importance? In SQL: ORDER BY (CASE WHEN railway='rail' THEN 5 WHEN railway='monorail' THEN 4 WHEN railway IN ('funicular','light_rail') THEN 3 etc......

On which server and which coverage (worldwide?) did you do the dry run?

**Comment by max-dn** [comment]
> What about sorting the rails to look at by their importance?

I thing sorting by distance is the better way. In most cases there are 1..3 rails nearby and it's hard to decide whats more important. A railway=light_rail in 20m distance or a rail in 10m... 
[in the test region](https://geo.dianacht.de/otmtest/stations3.html) it looks good, some ugly red labels show funny [railway=halt near abandoned](http://www.openstreetmap.org/#map=17/49.69029/10.97040) rails and something like [tram_stops tagged as stations](http://www.openstreetmap.org/node/1582352596). These "halts" are also shown on osm carto, so its ok...

About rendering:
![rotated stations](http://geo.dianacht.de/bilder/otm_stationrotate.png)
Maybe we have to change the icons later, i'm not very good in painting 10x10px... rw=halt are rendered in Z14-17 and are slightly smaller (10%) than rw=station, label size is the same. stations without rotation get a square label like before.

**Comment by der-stefan** [comment]
In your test there is a good example of the wrong decision of a rail track: [Erlangen-Bruck](https://geo.dianacht.de/otmtest/stations3.html?zoom=17&lat=49.56971&lon=10.99765&layers=0BTT) gets rotated like the branching rail. The main track goes from north to south. All the rest looks phenomenal! About the icons: We could change those icons later - creating pixel detailed icons is what I like a lot! :)

**Comment by max-dn** [comment]
Short rails were ignored at the limit was too high for the 2 rails next Erlangen Bruck. Now it's 50m and Erlangen Bruck hast direction 9, same as the next station "Paul-Gossen-Straße".

I made a pull request, let's see what happen ;)

**Comment by der-stefan** [comment]
Great work, @max-dn! Your pull request was merged and is online now. Btw: Processing time was 8 minutes.
