### ISSUE TITLE
add municipal boundaries (admin_level=8)

### ISSUE THREAD

**Issue by tstapff** [der-stefan/OpenTopoMap#97]
Official german topographic maps have them at 1:25000, which is roughly  zoom 14. Suggestion:

	<Rule>
		&maxscale_zoom14;
		&minscale_zoom17;
		<Filter>([admin_level] = '8')</Filter>
		<LineSymbolizer stroke="#c82fe5" stroke-width="0.5" stroke-dasharray="5.0 2.0" />
	</Rule>

**Comment by max-dn** [comment]
Rendering dashed borders like in [openstreetmap-carto](https://github.com/gravitystorm/openstreetmap-carto/blob/d501ba1acb7fa382e7b23e1574605daf7046224b/admin.mss) is a lot of work... Each border line on the map may be a stack of borders of different admin_levels and each border is represented by two borders (one for each neighbour), what leads to two overlaying lines with shifted dashes. 

In osm-carto this problem is solved by a invisible grounding of each border, so only the last line is visible. Maybe something with thinner lines is easier... But we can also try to adopt the osm-carto style.

**Comment by der-stefan** [comment]
Dashed borders would not appear the way they do on professional topographic maps: Often borders and streets/paths ("highways" ;-) ) share the same way. That makes it impossible to use a thin, dashed line. Either you can't distinguish it from footpaths or it hides behind roads/tracks/streets. That's why we have those purple borders.
